using System.Text;
using Backend.Data;
using Backend.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);

// Add Controllers
builder.Services.AddControllers();

// Configure the PostgreSQL DbContext for the Render deployment.
builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(
        builder.Configuration.GetConnectionString("DefaultConnection")
        ?? throw new InvalidOperationException("ConnectionStrings:DefaultConnection must be configured.")));

// Register AuthService
builder.Services.AddScoped<IAuthService, AuthService>();

// Configure JWT Authentication
var secretKey = builder.Configuration["Jwt:Secret"]
    ?? throw new InvalidOperationException("Jwt:Secret must be configured.");
var key = Encoding.UTF8.GetBytes(secretKey);

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.RequireHttpsMetadata = false;
    options.SaveToken = true;
    options.Events = new JwtBearerEvents
    {
        OnMessageReceived = context =>
        {
            // Read the JWT from the HttpOnly cookie instead of exposing it to JavaScript.
            context.Token = context.Request.Cookies["bookapp_auth"];
            return Task.CompletedTask;
        }
    };
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuerSigningKey = true,
        IssuerSigningKey = new SymmetricSecurityKey(key),
        ValidateIssuer = true,
        ValidIssuer = builder.Configuration["Jwt:Issuer"] ?? "BookAppApi",
        ValidateAudience = true,
        ValidAudience = builder.Configuration["Jwt:Audience"] ?? "BookAppClient",
        ClockSkew = TimeSpan.Zero
    };
});

builder.Services.AddAuthorization();

// Configure CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        var configuredOrigin = builder.Configuration["Cors:AllowedOrigins:0"];
        var allowedOrigins = string.IsNullOrWhiteSpace(configuredOrigin)
            ? new[] { "http://localhost:4200", "https://localhost:4200" }
            : new[] { configuredOrigin };

        policy.WithOrigins(allowedOrigins)
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});

var app = builder.Build();

// Create the PostgreSQL schema and seed data on first deployment.
using (var scope = app.Services.CreateScope())
{
    var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();
    dbContext.Database.ExecuteSqlRaw("""
        CREATE TABLE IF NOT EXISTS "Users" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Username" text NOT NULL,
            "PasswordHash" text NOT NULL
        );

        CREATE TABLE IF NOT EXISTS "Books" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Title" text NOT NULL,
            "Author" text NOT NULL,
            "PublishDate" timestamp without time zone NOT NULL,
            "UserId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS "Quotes" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Text" text NOT NULL,
            "Author" text NOT NULL,
            "UserId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE CASCADE
        );

        INSERT INTO "Users" ("Id", "Username", "PasswordHash")
        VALUES (1, 'seed-owner', 'seed-placeholder')
        ON CONFLICT ("Id") DO NOTHING;

        INSERT INTO "Books" ("Id", "Title", "Author", "PublishDate", "UserId")
        VALUES
            (1, 'Sagan om Ringen', 'J.R.R. Tolkien', '1954-07-29', 1),
            (2, '1984', 'George Orwell', '1949-06-08', 1),
            (3, 'Stolthet och fördom', 'Jane Austen', '1813-01-28', 1)
        ON CONFLICT ("Id") DO NOTHING;

        INSERT INTO "Quotes" ("Id", "Text", "Author", "UserId")
        VALUES
            (1, 'Det enda vi har att frukta är fruktan själv.', 'Franklin D. Roosevelt', 1),
            (2, 'Ett osökande liv är inte värt att leva.', 'Sokrates', 1),
            (3, 'Bli den förändring du vill se i världen.', 'Mahatma Gandhi', 1),
            (4, 'Det är aldrig för sent att bli vad du kunde ha varit.', 'George Eliot', 1),
            (5, 'Kunskap är makt.', 'Francis Bacon', 1)
        ON CONFLICT ("Id") DO NOTHING;

        SELECT setval(pg_get_serial_sequence('"Users"', 'Id'), COALESCE(MAX("Id"), 1), true) FROM "Users";
        SELECT setval(pg_get_serial_sequence('"Books"', 'Id'), COALESCE(MAX("Id"), 1), true) FROM "Books";
        SELECT setval(pg_get_serial_sequence('"Quotes"', 'Id'), COALESCE(MAX("Id"), 1), true) FROM "Quotes";
        """);
}

app.UseCors("AllowFrontend");

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();
